### ISSUE TITLE
Some Keyword missed and unexpected in .yml files

### ISSUE THREAD

**Issue by GaengSu** [swyoon/normalized-autoencoders#2]
안녕하세요. Sample Code를 돌려보다 몇가지 에러가 발생해서 여쭤봅니다.

1. `python train.py --config configs/mnist_ood_nae/z32.yml --logdir results/mnist_ood_nae/ --run run --device 0`
실행시 'unexpected keyword argument' 에러가 발생하는데, yml파일에 쓰여진 deterministic, sigma, sigma_trainable이 models/__init__.py의 NAE 생성자에 없는 것으로 보입니다. 

2. 위의 keyword 3개를 yml파일에서 삭제하고 실행했을 때 omegaconf.errors.ConfigKeyError: Missing key clip_grad 에러가 발생합니다. 논문을 바탕으로 yml파일의 training: 하위에  clip_grad: 0.01 를 작성하고 실행해도 omegaconf.errors.ConfigKeyError: Missing key small_D_lr 에러가 발생합니다.

에러에 대해 제가 잘못 실행한 점이 있거나 수정방안을 알려주시면 감사하겠습니다!

------------------
Hello :)
Some error occurred while running the sample code.

1. When i run `python train.py --config configs/mnist_ood_nae/z32.yml --logdir results/mnist_ood_nae/ --run run --device 0`, 'unexpected keyword argument'  is printed and an error occurs. it sems to be missing some keyword(deterministic, sigma) in the yml file.

2. When 3 keywords are deleted and running, 'omegaconf.errors.ConfigKeyError: Missing key clip_grad' is printed and error occurs.

I would appreciate it if you could let me know if there was something wrong with the error or how to correct it!

**Comment by swyoon** [comment]
보고해주신 에러를 해결하여 업로드해두었습니다. cifar와 mnist에 대해서 training이 돌아가는 것을 확인하였습니다.

1. 해당 keyword argument들을 지웠습니다.
2. OmegaConf의 최신 버젼(2.1.0)에서 key가 없는 경우의 정책이 바뀌어서 발생하는 에러였습니다. 기존에 제가 사용하던OmegaConf 버젼(2.0.6)에서는 key가 없으면 그냥 None을 반환했었습니다.

학습하는 부분을 제가 꼼꼼히 보지 못해서 죄송합니다. 다른 문제점이나 질문 있으면 언제든지 알려주세요.

=======

I have fixed the reported problems. The training code now works for MNIST and CIFAR-10 without errors.

1. I have deleted the keyword arguments.
2. The error is due to the changed behavior of OmegaConf for missing keys in the newest version (2,1.0). In the version I used, OmegaConf simply returns None when there was no matched key.

Thank you for reporting the issue. Please let me know if there is another problem or question.

Have a nice day!

**Comment by GaengSu** [comment]
> 보고해주신 에러를 해결하여 업로드해두었습니다. cifar와 mnist에 대해서 training이 돌아가는 것을 확인하였습니다.
> 
> 1. 해당 keyword argument들을 지웠습니다.
> 2. OmegaConf의 최신 버젼(2.1.0)에서 key가 없는 경우의 정책이 바뀌어서 발생하는 에러였습니다. 기존에 제가 사용하던OmegaConf 버젼(2.0.6)에서는 key가 없으면 그냥 None을 반환했었습니다.
> 
> 학습하는 부분을 제가 꼼꼼히 보지 못해서 죄송합니다. 다른 문제점이나 질문 있으면 언제든지 알려주세요.
> 
> =======
> 
> I have fixed the reported problems. The training code now works for MNIST and CIFAR-10 without errors.
> 
> 1. I have deleted the keyword arguments.
> 2. The error is due to the changed behavior of OmegaConf for missing keys in the newest version (2,1.0). In the version I used, OmegaConf simply returns None when there was no matched key.
> 
> Thank you for reporting the issue. Please let me know if there is another problem or question.
> 
> Have a nice day!

안녕하세요. 저번에 말씀드린 부분 중 일부가 수정이 되지 않은 것 같습니다.
train.py 57 line의 clip_grad와 nae.py 39 line의 small_lr_D 부분은 아직 남아있는데, yml파일에는 두 keyword가 존재하지 않아 run이 안되고 있습니다.
