### ISSUE TITLE
Some unexpected keyword augments when constructing the model

### ISSUE THREAD

**Issue by GloryyrolG** [swyoon/normalized-autoencoders#5]
Hi,

Thanks for great work and share. May I ask if it seems to have some problems with the provided .yml files? Like for CelebA64, `delta`, `deterministic`, etc.

https://github.com/swyoon/normalized-autoencoders/blob/0c77f7e29289e336c0fe5e941aaec8baa4a4fb82/configs/celeba64_ood_nae/z64gr_h32g8.yml#L21

```bash
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    run(cfg, writer)
  File "train.py", line 45, in run
    model = get_model(cfg).to(device)
  File "normalized-autoencoders/models/__init__.py", line 226, in get_model
    model = model(**model_dict)
  File "normalized-autoencoders/models/__init__.py", line 210, in get_nae
    ae = NAE(encoder, decoder, **model_cfg["nae"])
TypeError: __init__() got an unexpected keyword argument 'delta'
```

**Comment by swyoon** [comment]
Dear @GloryyrolG ,

Thank you for your attention to our work and also sorry for my negligence.

I have updated the configuration file so that CelebA training now runs without error. I have also updated the readme.

Please let me know if there's any other problem or question.

Have a nice day!

Sangwoong.
