### ISSUE TITLE
Not Good Quality of the Generated Images on CIFAR-10

### ISSUE THREAD

**Issue by GloryyrolG** [swyoon/normalized-autoencoders#6]
Hi SW,

I just found the generated images look not reasonable on CIFAR-10 (via your ckpt provided). Is it expected?

Thanks & Regards,

**Comment by swyoon** [comment]
Dear @GloryyrolG 

In general, the quality of generated images for CIFAR-10 model is indeed not very good, compared to state-of-the-art generative models, and it is one of the directions for future research.

The image quality may depend on the hyper-parameters of sampling, such as the number of Langevin Monte Carlo steps. 
With `--zstep 180` and `--xstep 40`, the examples of generated images for CIFAR-10 should look like the following.
Larger `zstep` is required because the sample replay buffer is used during training.

![image](https://user-images.githubusercontent.com/10072033/146328732-0c6b2f6d-265b-42e5-b4ef-2495e42376fd.png)

I will update the Readme with the guide for the `sample.py`.

Please let me know if there's another issue.

Best,
Sangwoong Yoon.

**Comment by GloryyrolG** [comment]
Thanks for your confirmation and explanations.

**Comment by swyoon** [comment]
The readme has been updated. Have a nice day!
