### ISSUE TITLE
pos_out > neg_out

### ISSUE THREAD

**Issue by GloryyrolG** [swyoon/normalized-autoencoders#8]
Hi SW @swyoon ,

As far as I know, the expectation of EBM training at least should be pos_out <= neg_out, right? However, I found in the exp of CelebA 64, we end up early where pos_out > neg_out.

![image](https://user-images.githubusercontent.com/33202229/146725068-e9a1aba8-2c39-47c8-892b-289fc2996120.png)

**Comment by swyoon** [comment]
Dear @GloryyrolG , 

Thank you for your observation. 

You are right about `pos_energy` <= `neg_energy` in general energy-based models. However, in NAE, we regularize `(neg_energy ** 2)` in order to prevent a model from diverging. I think this regularization is responsible for a slightly smaller `neg_energy`. From my experience, it is usually fine as long as pos_energy stays not too far from neg_energy.

Please let me know if you observe any notable consequences.

Best,
Sangwoong.
